### ISSUE TITLE
Slack alert not occuring.

### ISSUE THREAD

**Issue by jishnug007** [johnsusek/praeco#177]
I'm using searchguard elasticsearch. When connecting praeco to ES data and indices reaching in praeco. But when generating test alerts following error occured.
```
WARNING:elasticsearch:GET http://<es_ip>:9200/ [status:N/A request:0.006s]
Traceback (most recent call last):
  File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/node/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/node/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/node/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/node/.local/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 124, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/home/node/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/node/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

What are the possible problems and solutions?

Thank you.

**Comment by daichi703n** [comment]
Hi, @jishnug007 
It seems to be occured by miss settings. Did you set `ssl` options in `elastalert.yaml`?
https://github.com/ServerCentral/praeco/blob/master/config/elastalert.yaml#L26

I'm not using SearchGuard, but HTTPS(SSL) is enabled on Elasticsearch same as SearchGuard. (HTTPS is force enabled by SearchGuard.)

I succeeded in reproducing.

- `api.config.json`: `es_ssl: true`
- `elastalert.yaml`: `use_ssl: false` (or comment out)

Slack alert not occured and error occured.

```
01:04:12.403Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET http://elasticsearch:9200/ [status:N/A request:0.006s]
    Traceback (most recent call last):
      File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
        chunked=chunked)
      File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
        six.raise_from(e, None)
      File "<string>", line 2, in raise_from
      File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
        httplib_response = conn.getresponse()
      File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
        response.begin()
      File "/usr/lib/python3.6/http/client.py", line 297, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
        raise RemoteDisconnected("Remote end closed connection without"
    http.client.RemoteDisconnected: Remote end closed connection without response

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/node/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/home/node/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/home/node/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
        chunked=chunked)
      File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
        six.raise_from(e, None)
      File "<string>", line 2, in raise_from
      File "/home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
        httplib_response = conn.getresponse()
      File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
        response.begin()
      File "/usr/lib/python3.6/http/client.py", line 297, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
        raise RemoteDisconnected("Remote end closed connection without"
    urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/node/.local/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 124, in perform_request
        response = self.session.send(prepared_request, **send_kwargs)
      File "/home/node/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/home/node/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by johnsusek** [comment]
Make sure use_ssl is true, thanks
