### ISSUE TITLE
api 404 and elasticsearch error

### ISSUE THREAD

**Issue by vikas-prabhakar** [johnsusek/praeco#205]
getting below error on running elastalert server.
config/config.json & config/elasticesearch.yml is already updated with correct es host

on praeco gui is showing elasticsearch error 

logs of  elastalert-server
Elasticsearch ERROR: 2020-05-11T20:18:30Z
  Error: Request error, retrying
  POST http://elastalert/:********/elastalert_status/elastalert/_search => getaddrinfo ENOTFOUND elastalert
      at Log.error (/opt/elastalert-server/node_modules/elasticsearch/src/lib/log.js:226:56)
      at checkRespForFailure (/opt/elastalert-server/node_modules/elasticsearch/src/lib/transport.js:259:18)
      at HttpConnector.<anonymous> (/opt/elastalert-server/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
      at ClientRequest.wrapper (/opt/elastalert-server/node_modules/lodash/lodash.js:4929:19)
      at ClientRequest.emit (events.js:310:20)
      at Socket.socketErrorListener (_http_client.js:426:9)
      at Socket.emit (events.js:310:20)
      at emitErrorNT (internal/streams/destroy.js:92:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by vikas-prabhakar** [comment]
There is an issue while we are trying to use strong password like with some special characters i.e '#'
It's tough to debug as elastalert was able to create index but while preaco calls it's api it doesn't print any useful logs
