### ISSUE TITLE
Self signed cert issue - unable to verify the first certificate

### ISSUE THREAD

**Issue by scott-oit** [johnsusek/praeco#213]
I'm getting the following error in my console when I view a rule. (FQDN is replacing my the real server name).

    elastalert_1  | Elasticsearch ERROR: 2020-06-15T20:03:37Z
    elastalert_1  |   Error: Request error, retrying
    elastalert_1  |   POST https://FQDN:9200/fortigate-*/_search => unable to verify the first certificate
    elastalert_1  |       at Log.error (/opt/elastalert-server/node_modules/elasticsearch/src/lib/log.js:239:56)
    elastalert_1  |       at checkRespForFailure (/opt/elastalert-server/node_modules/elasticsearch/src/lib/transport.js:298:18)
    elastalert_1  |       at HttpConnector.<anonymous> (/opt/elastalert-server/node_modules/elasticsearch/src/lib/connectors/http.js:171:7)
    elastalert_1  |       at ClientRequest.wrapper (/opt/elastalert-server/node_modules/lodash/lodash.js:4929:19)
    elastalert_1  |       at ClientRequest.emit (events.js:315:20)
    elastalert_1  |       at TLSSocket.socketErrorListener (_http_client.js:467:9)
    elastalert_1  |       at TLSSocket.emit (events.js:315:20)
    elastalert_1  |       at emitErrorNT (internal/streams/destroy.js:100:8)
    elastalert_1  |       at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    elastalert_1  |       at processTicksAndRejections (internal/process/task_queues.js:84:21)
    elastalert_1  |
    elastalert_1  | Elasticsearch WARNING: 2020-06-15T20:03:37Z
    elastalert_1  |   Unable to revive connection: https://FQDN:9200/
    elastalert_1  |
    elastalert_1  | Elasticsearch WARNING: 2020-06-15T20:03:37Z
    elastalert_1  |   No living connections

I recently enabled SSL on ES with a signed cert from an untrusted source. It looks like elastalert can talk to Elastic some of the time. Here is my configuration Any ideas?

config/api.config.json

    {
      "appName": "elastalert-server",
      "port": 3030,
      "wsport": 3333,
      "elastalertPath": "/opt/elastalert",
      "verbose": false,
      "es_debug": false,
      "debug": false,
      "rulesPath": {
        "relative": true,
        "path": "/rules"
      },
      "templatesPath": {
        "relative": true,
        "path": "/rule_templates"
      },
      "es_host": "FQDN",
      "es_port": 9200,
      "es_username": "user",
      "es_password": "pass",
      "es_ssl": true,
      "writeback_index": "praeco_elastalert_status"
    }

./config/elastalert.json

    es_host: fqdn
    es_port: 9200
    rules_folder: rules
    run_every:
      seconds: 300
    buffer_time:
      minutes: 15
    #es_url_prefix: elasticsearch
    use_ssl: True
    #verify_certs:  False
    ca_certs: /opt/cacert/wil-ca64.cer #passing cert with docker-compose
    es_username: user
    es_password: pass
    writeback_index: praeco_elastalert_status
    alert_time_limit:
      days: 2
    skip_invalid: True

**Comment by johnsusek** [comment]
Does setting `verify_certs: False` in your rule yaml fix it?

**Comment by johnsusek** [comment]
Might need to add an option to elastalert.json for this if putting that in the rule yaml fixes it

**Comment by scott-oit** [comment]
I tried adding `verify_certs: false` and `verify_certs: False` to on of my rules and it still has the issue.
The rules still seem to run; I'm still getting alerts.

**Comment by itshusi** [comment]
Also got this same issue. @scott-oit did you manage to fix it or start an issue with bitsensor/elastalert? 
I don't think its a Yelp elastalert issue as it works for me from there without using your API (forked originally from bitsensor)

**Comment by scott-oit** [comment]
Hi @itshusi. Yes, but not with johnsusek's fork of elastalert. I am using a patched version of Elastalert by daichi703n. Daichi703n made some modifications and submitted them to elalastert, but I don't know if they ever got pulled. Here is current dockercompose file:

    version: '3'
    services:
      elastalert:
        image: 'daichi703n/elastalert:0.2.1-dev'
        ports:
          - '3030:3030'
          - '3333:3333'
        volumes:
          - ./config/elastalert.yaml:/opt/elastalert/config.yaml
          - ./config/api.config.json:/opt/elastalert-server/config/config.json
          - ./rules:/opt/elastalert/rules
          - ./rule_templates:/opt/elastalert/rule_templates
          - ./cert-ca64.cer:/opt/cacert/cert-ca64.cer
          - ./cert-ca64.cer:/opt/cacert/cert-ca64.crt
          - ./cert-ca64.cer:/usr/local/share/ca-certificates/cert-ca64.crt
        extra_hosts:
          - 'siem.internal.domain:10.0.0.2'
          - 'elasticsearch:10.0.0.2'
        restart: always
    
      webapp:
        image: 'johnsusek/praeco'
        restart: always
        ports:
          - '8080:8080'
        volumes:
          - ./public/praeco.config.json:/var/www/html/praeco.config.json
          - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
        network_mode: "host"

In my elastalert.yaml, Add the following `ca_certs: /opt/cacert/cer-ca64.crt`. 

I was trying a lot of things to get it to work, so I may have missed something or some of the config may not be needed.

**Comment by itshusi** [comment]
Hi @scott-oit, 
Thanks so much for your suggestion - I spent hours trying to fix this and regenerate new certificates only for your advice resulting in Praeco/Elastalert working within minutes! :)

**Comment by scott-oit** [comment]
I'm glad I am able to return some of the help I've got :)

**Comment by nsano-rururu** [comment]
@scott-oit @itshusi 

The following issue shows that it is a bug (implementation bug captured by pull request), and the ssl bug has been resolved in the current latest version.
https://github.com/johnsusek/praeco/issues/229

docker images
https://hub.docker.com/u/praecoapp
