### ISSUE TITLE
npm install unsuccessful - praeco

### ISSUE THREAD

**Issue by rajeshkalluri009** [johnsusek/praeco#217]
I am trying to install praeco manually as root login in Ubuntu 16.04.
I am getting the error at this phase. Some one please assist. 
npm install 
> nodent-runtime@3.2.1 install /etc/praeco/node_modules/nodent-runtime
> node build.js

fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open '/etc/praeco/node_modules/nodent-runtime/dist/index.js'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.<anonymous> (/etc/praeco/node_modules/nodent-runtime/build.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco/issues/191#issuecomment-594582151
>I have not tested with node 13. Manual installation is unsupported (that doesn't mean it won't work, it just means I don't have the time to help fix issues). I would highly recommend using the docker image or an environment close to the docker image.

Praeco recommends using Docker

**Comment by nsano-rururu** [comment]
@rajeshkalluri009

>Error: EACCES: permission denied, open '/etc/praeco/node_modules/nodent-runtime/dist/index.js'

try to execute npm install as non root user

**Comment by nsano-rururu** [comment]
@rajeshkalluri009

What is your current situation?
