### ISSUE TITLE
ModuleNotFoundError: No module named

### ISSUE THREAD

**Issue by kakaNo1** [johnsusek/praeco#220]
elastalert.yaml
```
es_host: 172.16.3.188
es_port: 32329
rules_folder: rules
run_every:
  seconds: 60
buffer_time:
  minutes: 1
writeback_index: praeco_elastalert_status
alert_time_limit:
  days: 2
skip_invalid: True
```
The API test:
```
[root@registry praeco]# curl 172.16.3.188:32329
{
  "name" : "ca_elasticsearch_test1",
  "cluster_name" : "ca_elasticsearch_test",
  "cluster_uuid" : "UbGeNVknRr6Rql1pdqyNSQ",
  "version" : {
    "number" : "7.2.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "508c38a",
    "build_date" : "2019-06-20T15:54:18.811730Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
api.config.json
```
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "172.16.3.188",
  "es_port": 32329,
  "es_username": "",
  "es_password": "",
  "es_ssl": false,
  "writeback_index": "praeco_elastalert_status"
}
```
[root@registry  praeco]# docker-compose up
```
Creating praeco_webapp_1     ... done
Creating praeco_elastalert_1 ... done
Attaching to praeco_webapp_1, praeco_elastalert_1
elastalert_1  |
elastalert_1  | > @bitsensor/elastalert@0.0.14 start /opt/elastalert-server
elastalert_1  | > sh ./scripts/start.sh
elastalert_1  |
elastalert_1  | 09:28:29.838Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
elastalert_1  | 09:28:29.845Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
elastalert_1  | 09:28:29.872Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
elastalert_1  | 09:28:29.904Z  INFO elastalert-server: Router:  Listening for GET request on /.
elastalert_1  | 09:28:29.904Z  INFO elastalert-server: Router:  Listening for GET request on /status.
elastalert_1  | 09:28:29.905Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
elastalert_1  | 09:28:29.905Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
elastalert_1  | 09:28:29.907Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id*.
elastalert_1  | 09:28:29.907Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id*.
elastalert_1  | 09:28:29.908Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id*.
elastalert_1  | 09:28:29.908Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
elastalert_1  | 09:28:29.908Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id*.
elastalert_1  | 09:28:29.908Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id*.
elastalert_1  | 09:28:29.909Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id*.
elastalert_1  | 09:28:29.909Z  INFO elastalert-server: Router:  Listening for PUT request on /folders/:type/:path*.
elastalert_1  | 09:28:29.909Z  INFO elastalert-server: Router:  Listening for DELETE request on /folders/:type/:path*.
elastalert_1  | 09:28:29.913Z  INFO elastalert-server: Router:  Listening for POST request on /test.
elastalert_1  | 09:28:29.913Z  INFO elastalert-server: Router:  Listening for POST request on /silence/:path*.
elastalert_1  | 09:28:29.913Z  INFO elastalert-server: Router:  Listening for GET request on /config.
elastalert_1  | 09:28:29.913Z  INFO elastalert-server: Router:  Listening for POST request on /config.
elastalert_1  | 09:28:29.913Z  INFO elastalert-server: Router:  Listening for POST request on /download.
elastalert_1  | 09:28:29.914Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert.
elastalert_1  | 09:28:29.914Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_status.
elastalert_1  | 09:28:29.914Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/silence.
elastalert_1  | 09:28:29.914Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_error.
elastalert_1  | 09:28:29.914Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/past_elastalert.
elastalert_1  | 09:28:29.914Z  INFO elastalert-server: Router:  Listening for GET request on /indices.
elastalert_1  | 09:28:29.915Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
elastalert_1  | 09:28:29.915Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
elastalert_1  | 09:28:29.915Z  INFO elastalert-server: Router:  Listening for GET request on /config.
elastalert_1  | 09:28:29.924Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
elastalert_1  | 09:28:29.924Z  INFO elastalert-server: ProcessController:  Creating index
elastalert_1  | 09:28:29.971Z ERROR elastalert-server:
elastalert_1  |     ProcessController:  Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 184, in _run_module_as_main
elastalert_1  |         mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 110, in _get_module_details
elastalert_1  |         __import__(pkg_name)
elastalert_1  |       File "/opt/elastalert/elastalert/__init__.py", line 5, in <module>
elastalert_1  |         from elasticsearch import Elasticsearch
elastalert_1  |     ModuleNotFoundError: No module named 'elasticsearch'
elastalert_1  |
elastalert_1  | 09:28:29.971Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
elastalert_1  | 09:28:29.971Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
elastalert_1  | 09:28:29.972Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
elastalert_1  | 09:28:29.984Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 36)
elastalert_1  | 09:28:29.986Z  INFO elastalert-server: Server:  Server listening on port 3030
elastalert_1  | 09:28:29.986Z  INFO elastalert-server: Server:  Websocket listening on port 3333
elastalert_1  | 09:28:29.987Z  INFO elastalert-server: Server:  Server started
elastalert_1  | 09:28:30.021Z ERROR elastalert-server:
elastalert_1  |     ProcessController:  Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 184, in _run_module_as_main
elastalert_1  |         mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 110, in _get_module_details
elastalert_1  |         __import__(pkg_name)
elastalert_1  |       File "/opt/elastalert/elastalert/__init__.py", line 5, in <module>
elastalert_1  |         from elasticsearch import Elasticsearch
elastalert_1  |     ModuleNotFoundError: No module named 'elasticsearch'
elastalert_1  |
elastalert_1  | 09:28:30.027Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping praeco_webapp_1     ... done
Stopping praeco_elastalert_1 ... done
```
docker-compose.yml
```
version: '3'

services:
  elastalert:
    image: 'johnsusek/elastalert-server'
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
    extra_hosts:
      - 'elasticsearch:172.16.3.188'

  webapp:
    image: 'johnsusek/praeco'
    ports:
      - 8080:8080
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
```

**Comment by nsano-rururu** [comment]
@kakaNo1 

If you run Elasticsearch without running it, you get the error. Elasticsearch must be running first.

**Comment by nsano-rururu** [comment]
The settings look fine.
This error has never occurred.

**Comment by nsano-rururu** [comment]
The error could not be reproduced.

johnsusek/elastalert-server
johnsusek/praeco
Elasticsearch 7.2.0
Kibana 7.2.0

```
/home/sano/dkwork2/es
|--Dockerfiles
|  |--Dockerfile.elastalert
|--docker-compose.yml
|--es
|  |--config
|  |  |--elasticsearch.yml
|  |--data
|--kibana
|  |--config
|  |  |--kibana.yml
|--praeco
|  |--bin
|  |  |--elastalert-start.sh
|  |  |--elastic_search_status.sh
|  |--config
|  |  |--api.config.json
|  |  |--elastalert.yaml
|  |--nginx_config
|  |  |--default.conf
|  |  |--nginx.conf
|  |--public
|  |  |--favicon.ico
|  |  |--index.html
|  |  |--js
|  |  |  |--cron-ui.min.js
|  |  |--praeco.config.json
|  |--rule_templates
|  |--rules
```

**Dockerfiles/Dockerfile.elastalert**

```
FROM johnsusek/elastalert-server 

USER root

RUN apk add --update --no-cache net-snmp net-snmp-tools
RUN apk update && \
    apk add bash curl && \
    rm -rf /var/cache/apk/*

ADD praeco/bin/elastalert-start.sh /usr/local/bin/
ADD praeco/bin/elastic_search_status.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/elastalert-start.sh 
RUN chmod +x /usr/local/bin/elastic_search_status.sh

USER node

ENTRYPOINT ["/usr/local/bin/elastalert-start.sh"]
```

**docker-compose.yml**

```
version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
      - discovery.type=single-node
    restart: always
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 180s

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
 
  elastalert:
    container_name: elastalert
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.elastalert
    image: elastalert-server:0.2.4
    ports:
      - 3030:3030
      - 3333:3333
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./praeco/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./praeco/config/api.config.json:/opt/elastalert-server/config/config.json
      - ./praeco/rules:/opt/elastalert/rules
      - ./praeco/rule_templates:/opt/elastalert/rule_templates
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s

  praeco:
    container_name: praeco
    image: johnsusek/praeco
    ports:
      - 8080:8080
    depends_on:
      - elastalert
    restart: always
    volumes:
      - ./praeco/public/praeco.config.json:/var/www/html/praeco.config.json
      - ./praeco/nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./praeco/nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
```


**es/config/elasticsearch.yml**

```
cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
```

**kibana/config/kibana.yml**

```
server.name: kibana
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
```

**praeco/bin/elastalert-start.sh**

```
#!/bin/bash

set -e

echo "Giving Elasticsearch at $ELASTICSEARCH_URL time to start..."

elastic_search_status.sh

echo "Starting ElastAlert!"
npm start
```

**praeco/bin/elastic_search_status.sh**

```
#!/bin/bash

set -e

if [ $# -gt 0 ]; then
  ES_URL="$1"
elif [[ -n $ELASTICSEARCH_URL ]]; then
  ES_URL="$ELASTICSEARCH_URL"
elif [[ -n $ES_HOST ]] && [[ -n $ES_PORT ]]; then
  ES_URL="http://$ES_HOST:$ES_PORT"
else
  ES_URL="http://elasticsearch:9200"
fi

until [[ "$(curl -fsSL "$ES_URL/_cat/health?h=status" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')" =~ ^(yellow|green)$ ]]; do
  # printf '+' >&2
  sleep 1
done

echo "Elasticsearch is up and healthy at "$ES_URL"" >&2
```

**praeco/config/api.config.json**

Default settings

```
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elasticsearch",
  "es_port": 9200,
  "es_username": "",
  "es_password": "",
  "es_ssl": false,
  "writeback_index": "praeco_elastalert_status"
}
```

**praeco/config/elastalert.yaml**

Default settings

```
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: elasticsearch

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 60

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: praeco_elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True

profile: default
```

**praeco/public/praeco.config.json**

Default settings

```
{
  "appUrl": "http://127.0.0.1:8080",
  "errorLoggerUrl": "",
  "hidePreconfiguredFields": []
}
```

**execute**

```
chmod 777 es/data
chmod 777 praeco/rule_templates
chmod 777 praeco/rules
docker-compose up -d
docker logs -f elastalert

Giving Elasticsearch at  time to start...
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
curl: (7) Failed to connect to elasticsearch port 9200: Connection refused
Elasticsearch is up and healthy at http://elasticsearch:9200
Starting ElastAlert!

> @bitsensor/elastalert@0.0.14 start /opt/elastalert-server
> sh ./scripts/start.sh

14:23:35.503Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
14:23:35.514Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
14:23:35.515Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
14:23:35.527Z  INFO elastalert-server: Router:  Listening for GET request on /.
14:23:35.529Z  INFO elastalert-server: Router:  Listening for GET request on /status.
14:23:35.529Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
14:23:35.530Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
14:23:35.533Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id*.
14:23:35.534Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id*.
14:23:35.535Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id*.
14:23:35.536Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
14:23:35.537Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id*.
14:23:35.537Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id*.
14:23:35.538Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id*.
14:23:35.539Z  INFO elastalert-server: Router:  Listening for PUT request on /folders/:type/:path*.
14:23:35.540Z  INFO elastalert-server: Router:  Listening for DELETE request on /folders/:type/:path*.
14:23:35.540Z  INFO elastalert-server: Router:  Listening for POST request on /test.
14:23:35.541Z  INFO elastalert-server: Router:  Listening for POST request on /silence/:path*.
14:23:35.542Z  INFO elastalert-server: Router:  Listening for GET request on /config.
14:23:35.542Z  INFO elastalert-server: Router:  Listening for POST request on /config.
14:23:35.543Z  INFO elastalert-server: Router:  Listening for POST request on /download.
14:23:35.544Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert.
14:23:35.544Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_status.
14:23:35.545Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/silence.
14:23:35.546Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_error.
14:23:35.546Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/past_elastalert.
14:23:35.549Z  INFO elastalert-server: Router:  Listening for GET request on /indices.
14:23:35.550Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
14:23:35.550Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
14:23:35.550Z  INFO elastalert-server: Router:  Listening for GET request on /config.
14:23:35.558Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
14:23:35.559Z  INFO elastalert-server: ProcessController:  Creating index
14:23:40.599Z  INFO elastalert-server:
    ProcessController:  Elastic Version: 7.2.0
    Reading Elastic 6 index mappings:
    Reading index mapping 'es_mappings/6/silence.json'
    Reading index mapping 'es_mappings/6/elastalert_status.json'
    Reading index mapping 'es_mappings/6/elastalert.json'
    Reading index mapping 'es_mappings/6/past_elastalert.json'
    Reading index mapping 'es_mappings/6/elastalert_error.json'
    New index praeco_elastalert_status created
    Done!
    
14:23:40.599Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
14:23:40.600Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
14:23:40.618Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 260)
14:23:40.625Z  INFO elastalert-server: Server:  Server listening on port 3030
14:23:40.626Z  INFO elastalert-server: Server:  Websocket listening on port 3333
14:23:40.627Z  INFO elastalert-server: Server:  Server started
14:23:46.410Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:24:16.817Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:24:47.492Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:25:17.941Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:25:48.463Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:26:19.031Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:26:49.636Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:27:20.204Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:27:50.840Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:28:21.417Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:28:51.943Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:29:22.539Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
```

**Comment by nsano-rururu** [comment]
It is not recommended to use the settings written on the official website as they are. 
Most of the time, it doesn't work because it doesn't match my environment.

**Comment by nsano-rururu** [comment]
I'll try Elasticsearch to see if it runs on a different host than ElastAlert Server and Praeco, but if that's okay, it's a network or firewall issue. There is no choice but to squeeze each one that seems to be a problem.

**Comment by kakaNo1** [comment]
I'm also surprised that nothing has changed and this problem arises when running again, but I replaced it with JohnSusek /elastalert-server:1592081541 and everything works fine and I'm wondering if I can re-pull JohnSusek /elastalert- Server :latest and maybe the error will go away

**Comment by nsano-rururu** [comment]
JohnSusek/elastalert-server:1592081541 and JohnSusek/elastalert-Server:latest have the same DIGEST, so only the tag name is different in the same Docker image. So there should be no difference. Hmm. It's a mystery. Unfortunately I could not reproduce the problem in my environment.

■ Operation check environment
Amazon Workspases (OS: Amazon Linux2)
2 CPU, 7.5GiB Memory, 80GB
Docker version 19.03.6-ce, build 369ce74
Elasticsearch 7.2.0
Kibana 7.2.0
JohnSusek/elastalert- Server:latest

![キャプチャ](https://user-images.githubusercontent.com/22293449/87943509-1d821600-cad9-11ea-984b-f4c770fc720e.PNG)
