### ISSUE TITLE
unable to create rules in version praeco 1.3.0

### ISSUE THREAD

**Issue by shettypriy** [johnsusek/praeco#239]
I am trying to create rule in praeco version 1.3.0, but following error is got 
`Rule not found, it may have been moved or deleted.`

The logs show the following

```
Routes:  Request for '/rules/:id' failed with error: 
elastalert_1  |     
elastalert_1  |      TypeError: Cannot read property 'write' of undefined
elastalert_1  |         at Object.edit (/opt/elastalert-server/src/controllers/rules/index.js:91:26)
elastalert_1  |         at /opt/elastalert-server/src/handlers/rules/id/post.js:16:12
elastalert_1  | 10:05:36.354Z ERROR elastalert-server: RulesController:  Failed to _findRule(rule1) error: undefined

permission for rules folder is set to 755. I changed the permission to 777 still same issue. also able to connect to elasticsearch at curl http://$PRAECO_ELASTICSEARCH:9200
```
Could you please help

**Comment by nsano-rururu** [comment]
@shettypriy 

We released a modified version of Docker image. We apologize for any inconvenience.
https://hub.docker.com/r/praecoapp/elastalert-server

**Comment by vtdat** [comment]
Can confirm rule is created and works perfectly fine.

**Comment by shettypriy** [comment]
Now able to create rules in the version 1.3.. Thank you
