### ISSUE TITLE
AttributeError: 'str' object has no attribute 'update' when I try to test or create rule

### ISSUE THREAD

**Issue by jabibenito** [johnsusek/praeco#266]
hi,

I am trying to create test rule and show this error in the cli and on the web

`elastalert_1  | 07:35:46.296Z ERROR elastalert-server:
elastalert_1  |     TestController:  Failed to test rule with error: INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
elastalert_1  |                 To send them but remain verbose, use --verbose instead.
elastalert_1  |
elastalert_1  |     Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
elastalert_1  |         return _run_code(code, main_globals, None,
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
elastalert_1  |         exec(code, run_globals)
elastalert_1  |       File "/opt/elastalert/elastalert/test_rule.py", line 449, in <module>
elastalert_1  |         main()
elastalert_1  |       File "/opt/elastalert/elastalert/test_rule.py", line 445, in main
elastalert_1  |         test_instance.run_rule_test()
elastalert_1  |       File "/opt/elastalert/elastalert/test_rule.py", line 413, in run_rule_test
elastalert_1  |         rule_yaml = conf['rules_loader'].load_yaml(args.file)
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 207, in load_yaml
elastalert_1  |         loaded.update(rule)
elastalert_1  |     AttributeError: 'str' object has no attribute 'update'`

**Comment by nsano-rururu** [comment]
Is it a docker environment?

**Comment by nsano-rururu** [comment]
I'm about to go home by train after work. Find out about your home.

**Comment by jabibenito** [comment]
> Is it a docker environment?

Yes it is a docker environment.

**Comment by nsano-rururu** [comment]
Since the error may not be reproduced, please tell me what you operated on the screen.

**Comment by jabibenito** [comment]
> Since the error may not be reproduced, please tell me what you operated on the screen.

I have followed the next install steps:

- export PRAECO_ELASTICSEARCH=10.1.2.115
- Edited rules/BaseRule.config file with slack connector
- Edited config/api.config.json, config/elastalert.yaml and uncommented username and password and change the es_host

After that I have execute docker-compose up and access to praeco ui.

Inside the praeco ui I have followed this link https://medium.com/@john_8166/praeco-walkthrough-5aada7e078a9 and we I execute test rule I see this error.

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/12827502/96719694-0689e300-13aa-11eb-89ce-8ad0d0e512e4.png">

And If I click to save 

<img width="460" alt="image" src="https://user-images.githubusercontent.com/12827502/96719762-215c5780-13aa-11eb-96cb-7ad623e2bd9a.png">

I do not understand because all fields are completed.

**Comment by nsano-rururu** [comment]
Are you doing the following?

```
mkdir rules rule_templates
chmod -R 777 rules rule_templates
```

**Comment by nsano-rururu** [comment]
There were no problems.
![1](https://user-images.githubusercontent.com/22293449/96724300-a36c7080-13ea-11eb-8276-0dfa40b6742c.PNG)

![b](https://user-images.githubusercontent.com/22293449/96724281-9ea7bc80-13ea-11eb-9787-f2f88b901cee.PNG)

**Comment by nsano-rururu** [comment]
I don't use docker-compose on this site.
Because it's subtle. It is the setting of the following link destination.

https://github.com/johnsusek/praeco/issues/254#issuecomment-703104530

**Comment by jabibenito** [comment]
> Are you doing the following?
> 
> ```
> mkdir -p rules rule_templates
> chmod -R 777 rules rule_templates
> ```

I have changed permissions and still not work

**Comment by jabibenito** [comment]
> > Are you doing the following?
> > ```
> > mkdir -p rules rule_templates
> > chmod -R 777 rules rule_templates
> > ```
> 
> I have changed permissions and still not work

I have deleted these folders and create newly with permissions indicated above, and works fine.
