### ISSUE TITLE
[elastalert-server]npm 6.x.x→7.x.x

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#271]
When I raise it to npm 7.x.x, I get the following error.
That's why I'm currently using npm 6.14.8.

https://github.com/trentm/node-bunyan
https://www.npmjs.com/package/bunyan

```
Starting ElastAlert!

> @bitsensor/elastalert@0.0.14 start
> sh ./scripts/start.sh

./scripts/start.sh: line 3: ./node_modules/.bin/bunyan: not found
node:events:304
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:162:15)
    at writeGeneric (node:internal/stream_base_commons:153:3)
    at Socket._writeGeneric (node:net:763:11)
    at Socket._write (node:net:775:8)
    at writeOrBuffer (node:internal/streams/writable:388:12)
    at Socket.Writable.write (node:internal/streams/writable:333:10)
    at Logger._emit (/opt/elastalert-server/node_modules/bunyan/lib/bunyan.js:923:22)
    at Logger.info (/opt/elastalert-server/node_modules/bunyan/lib/bunyan.js:1045:24)
    at Logger.info (/opt/elastalert-server/src/common/logger/index.js:9:12)
    at /opt/elastalert-server/src/common/config/server_config.js:114:22
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
npm notice 
npm notice New patch version of npm available! 7.0.8 -> 7.0.9
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.9>
npm notice Run `npm install -g npm@7.0.9` to update!
npm notice 
npm ERR! code 127
npm ERR! path /opt/elastalert-server
npm ERR! command failed
npm ERR! command sh -c sh ./scripts/start.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-11-08T15_54_19_606Z-debug.log
```

**Comment by nsano-rururu** [comment]
| Name | Version | Update Date | node 7.x | 
| :--- | :---| :--- | :--- | 
|[molindo-node-logger](https://github.com/ekino/node-logger)|1.1.1|2020/10/26||
|[pino](https://github.com/pinojs/pino)|6.7.0|2020/10/06||
|[node-bunyan](https://github.com/trentm/node-bunyan)|2.0.4 (beta)<br>1.8.14|2020/06/29<br>2020/06/29||
|[winston](https://github.com/winstonjs/winston)|3.3.3|2020/06/24||
|[log4js-node](https://github.com/log4js-node/log4js-node)|6.3.0|2020/05/25||
|[node-logger](https://github.com/ekino/node-logger)|1.0.0|2020/03/26||
|[Simple Node Logger](https://github.com/darrylwest/simple-node-logger)|18.12.24|2020/01/16||

**Comment by nsano-rururu** [comment]
It turned out that it can be handled by adding cross-env. This issue will be closed as we will add it in the next release.
