### ISSUE TITLE
[Praeco]Library Update (Praeco 1.5.2)

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#280]
Scheduled to check operation after update

@vue/cli 4.4.6 → 4.5.9
https://github.com/vuejs/vue-cli

```
npm install -g npm-check-updates

npm install -g npm@7.2.0

# version check
$ vue --version
@vue/cli 4.4.6

# update
$ npm uninstall vue-cli -g
$ npm install -g @vue/cli

# version check
$ vue --version
```

```
 @babel/core                           7.11.6  →  7.12.10     
 @browser-bunyan/server-stream          1.5.3  →    1.6.1     
 @fortawesome/fontawesome-svg-core     1.2.30  →   1.2.32     
 @fortawesome/free-brands-svg-icons    5.14.0  →   5.15.1     
 @fortawesome/free-regular-svg-icons   5.14.0  →   5.15.1     
 @fortawesome/free-solid-svg-icons     5.14.0  →   5.15.1
 @fortawesome/vue-fontawesome           2.0.0  →    2.0.2    
 axios                                 0.20.0  →   0.21.1     
 browser-bunyan                         1.5.3  →    1.6.3     
 change-case                            4.1.1  →    4.1.2     
 core-js                               ^3.6.5  →   ^3.8.1     
 echarts                                4.9.0  →    5.0.0     
 element-ui                            2.13.2  →   2.14.1
 js-yaml                               3.14.0  →   3.14.1     
 moment                                2.29.0  →   2.29.1     
 moment-timezone                       0.5.31  →   0.5.32     
 prismjs                               1.21.0  →   1.23.0     
 semver                                 7.3.2  →    7.3.4
 vue-json-pretty                        1.6.7  →    1.7.1       
 vue-router                             3.4.3  →    3.4.9     
 vuex                                   3.5.1  →    3.6.0     
 vuex-persist                           3.1.0  →    3.1.3       
 zrender                                4.3.2  →    5.0.1     
 @vue/cli-plugin-babel                 ^4.5.6  →   ^4.5.9     
 @vue/cli-plugin-eslint                ^4.5.6  →   ^4.5.9     
 @vue/cli-plugin-unit-mocha            ^4.5.6  →   ^4.5.9     
 @vue/cli-service                      ^4.5.6  →   ^4.5.9     
 @vue/eslint-config-airbnb             ^5.1.0  →   ^5.3.0     
 @vue/test-utils                        1.1.0  →    1.1.2     
 axios-mock-adapter                    1.18.2  →   1.19.0     
 cross-env                              7.0.2  →    7.0.3     
 eslint                                ^7.9.0  →  ^6.8.0     
 eslint-plugin-cypress                ^2.11.1  →  ^2.11.2     
 eslint-plugin-import                 ^2.22.0  →  ^2.22.1        
 husky                                  4.3.0  →    4.3.6     
 node-sass                             4.14.1  →    5.0.0     
 sass-loader                           10.0.2  →   10.1.0  
```

```
# 
ncu -u @babel/core @browser-bunyan/server-stream @fortawesome/fontawesome-svg-core @fortawesome/free-brands-svg-icons @fortawesome/free-regular-svg-icons @fortawesome/free-solid-svg-icons axios browser-bunyan change-case core-js echarts element-ui js-yaml moment moment-timezone prismjs semver vue-json-pretty vue-router vuex vuex-persist zrender @vue/cli-plugin-babel @vue/cli-plugin-eslint @vue/cli-plugin-unit-mocha @vue/cli-service @vue/eslint-config-airbnb @vue/test-utils axios-mock-adapter cross-env eslint eslint-plugin-cypress eslint-plugin-import eslint-plugin-vue husky node-sass sass-loader 
npm install --save --legacy-peer-deps

[CORP\sano@a-ngft53r34ong praeco]$ npm run test:unit

> praeco@1.5.1 test:unit
> vue-cli-service test:unit

(node:17486) UnhandledPromiseRejectionWarning: Error: Cannot find module '../build/Release/canvas.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function._resolveFilename (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/mochapack/lib/util/registerRequireHook.js:26:36)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
(node:17486) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17486) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Not subject to update this time as problems will occur in operation

There is information that if you set vue-json-pretty to 2, you need to set it to vue 3.

```
 vue-echarts                            3.1.2  →    4.1.0     
webpack                                4.44.2 →    5.11.0
vue-json-pretty                        1.6.7  →    2.0.0
eslint-plugin-vue                     ^6.2.2  →   ^7.3.0
eslint                                ^7.17.0
vue-query-builder                     0.6.1 → 0.8.2          
```

**Comment by nsano-rururu** [comment]
Node.js


| Node.js| npm|npm run test:unit|
|---------|------|-------------------|
|10.23.0|6.14.9|OK|
|10.23.0|7.2.0|OK|
|11.15.0|6.14.9|NG|
|12.20.0|6.14.9|NG|
|13.14.0|6.14.9|NG|
|14.15.2|6.14.9|NG|
|15.4.0|6.14.9|NG|


Node.js 10.23.0
npm 6.14.9

```
npm install -g npm@6.14.9
nvm install 10.23.0
npm run test:unit

> praeco@1.5.1 test:unit /home/sano/dkwork3/elastalert_praeco/praeco
> vue-cli-service test:unit

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
 WEBPACK  Compiling...

  [=========================] 98% (after emitting)

 DONE  Compiled successfully in 23558ms

  [=========================] 100% (completed)

 WEBPACK  Compiled successfully in 23558ms

 MOCHA  Testing...



  ConfigAlert
    ✓ renders the realert amount (1784ms)
    ✓ renders the realert unit
    ✓ renders the right destination
    ✓ renders the right subject
    ✓ renders the right body
    ✓ renders the right slack channel
    ✓ renders the right slack user
    ✓ renders the right slack message color

  ConfigCondition log
    ✓ renders the numEvents (520ms)
    ✓ renders the aboveOrBelow
    ✓ renders the WHEN count
    ✓ renders the OVER all documents
    ✓ renders the UNFILTERED
    ✓ renders the GROUPED OVER field
    ✓ renders the timeframe interval
    ✓ renders the timeframe amount
    ✓ renders the WITH OPTIONS useCountQuery
    ✓ renders the WITH OPTIONS docType

  YAML parsing
    ✓ renders the correct yaml (72ms)

  Errors log
    ✓ renders the rule
    ✓ renders the error

  Queries log
    ✓ renders the query log correctly (821ms)

  RuleView
    ✓ renders the rule

  Silences log
    ✓ renders the silence log correctly (310ms)

  alertText
    ✓ returns config-formatted alert text
    ✓ returns html-formatted alert text

  luceneSyntaxBuilder
    ✓ returns correct query string given empty querybuilder tree
    ✓ returns correct query string given filled querybuilder tree
    ✓ returns correct query string given completely filled querybuilder tree


  29 passing (4s)

 MOCHA  Tests completed successfully
```

Node.js 10.23.0
npm 7.2.0

```
npm install -g npm@7.2.0
nvm install 10.23.0
npm run test:unit

> praeco@1.5.1 test:unit
> vue-cli-service test:unit

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
 WEBPACK  Compiling...

  [=========================] 98% (after emitting)

 DONE  Compiled successfully in 8153ms

  [=========================] 100% (completed)

 WEBPACK  Compiled successfully in 8153ms

 MOCHA  Testing...



  ConfigAlert
    ✓ renders the realert amount (2007ms)
    ✓ renders the realert unit
    ✓ renders the right destination
    ✓ renders the right subject
    ✓ renders the right body
    ✓ renders the right slack channel
    ✓ renders the right slack user
    ✓ renders the right slack message color

  ConfigCondition log
    ✓ renders the numEvents (486ms)
    ✓ renders the aboveOrBelow
    ✓ renders the WHEN count
    ✓ renders the OVER all documents
    ✓ renders the UNFILTERED
    ✓ renders the GROUPED OVER field
    ✓ renders the timeframe interval
    ✓ renders the timeframe amount
    ✓ renders the WITH OPTIONS useCountQuery
    ✓ renders the WITH OPTIONS docType

  YAML parsing
    ✓ renders the correct yaml (70ms)

  Errors log
    ✓ renders the rule
    ✓ renders the error

  Queries log
    ✓ renders the query log correctly (445ms)

  RuleView
    ✓ renders the rule

  Silences log
    ✓ renders the silence log correctly (308ms)

  alertText
    ✓ returns config-formatted alert text
    ✓ returns html-formatted alert text

  luceneSyntaxBuilder
    ✓ returns correct query string given empty querybuilder tree
    ✓ returns correct query string given filled querybuilder tree
    ✓ returns correct query string given completely filled querybuilder tree


  29 passing (4s)

 MOCHA  Tests completed successfully
```

Node.js 11.15.0
npm 6.14.9

```
npm install -g npm@6.14.9
nvm install 11.15.0
npm run test:unit

> praeco@1.5.1 test:unit /home/sano/dkwork3/elastalert_praeco/praeco
> vue-cli-service test:unit

(node:27741) UnhandledPromiseRejectionWarning: Error: The module '/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
(node:27741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27741) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Node.js 12.20.0
npm 6.14.9

```
npm install -g npm@6.14.9
nvm install 12.20.0
npm run test:unit

> praeco@1.5.1 test:unit /home/sano/dkwork3/elastalert_praeco/praeco
> vue-cli-service test:unit

(node:28213) UnhandledPromiseRejectionWarning: Error: The module '/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
(node:28213) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28213) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Node.js 13.14.0
npm 6.14.9

```
npm install -g npm@6.14.9
nvm install 13.14.0
npm run test:unit

> praeco@1.5.1 test:unit /home/sano/dkwork3/elastalert_praeco/praeco
> vue-cli-service test:unit

(node:28213) UnhandledPromiseRejectionWarning: Error: The module '/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
(node:28213) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28213) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Node.js 14.15.2
npm 6.14.9

```
npm install -g npm@6.14.9
nvm install 14.15.2
npm run test:unit

> praeco@1.5.1 test:unit /home/sano/dkwork3/elastalert_praeco/praeco
> vue-cli-service test:unit

(node:29192) UnhandledPromiseRejectionWarning: Error: The module '/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Node.js 15.4.0
npm 6.14.9

```
npm install -g npm@6.14.9
nvm install 15.4.0
npm run test:unit

> praeco@1.5.1 test:unit
> vue-cli-service test:unit

node:internal/modules/cjs/loader:1167
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 88. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1167:18)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'ERR_DLOPEN_FAILED'
}
 ERROR  mochapack exited with code 1.
npm ERR! code 1
npm ERR! path /home/sano/dkwork3/elastalert_praeco/praeco
npm ERR! command failed
npm ERR! command sh -c vue-cli-service test:unit

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sano/.npm/_logs/2020-12-16T15_00_25_945Z-debug.log
```

**Comment by nsano-rururu** [comment]
The following items need to be updated as a set

```
 node-sass                             4.14.1  →    5.0.0     
 sass-loader                           10.0.2  →   10.1.0  
```
