### ISSUE TITLE
Update vue-json-pretty(1.7.1→2.x.x)

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#289]
There is information that if you set vue-json-pretty to 2, you need to set it to vue 3.

```
[CORP\sano@a-ngft53r34ong praeco]$ npm run test:unit

> praeco@1.5.1 test:unit /home/sano/dkwork3/elastalert_praeco/praeco
> vue-cli-service test:unit

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
 WEBPACK  Compiling...

  [=========================] 98% (after emitting)

 DONE  Compiled successfully in 21931ms

  [=========================] 100% (completed)

 WEBPACK  Compiled successfully in 21931ms

 MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

TypeError: (0 , o.defineComponent) is not a function
    at Object.719 (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/node_modules/vue-json-pretty/lib/vue-json-pretty.js:1:1)
    at o (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/node_modules/vue-json-pretty/lib/vue-json-pretty.js:1:1)
    at /home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/node_modules/vue-json-pretty/lib/vue-json-pretty.js:1:1
    at /home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/node_modules/vue-json-pretty/lib/vue-json-pretty.js:1:1
    at /home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/node_modules/vue-json-pretty/lib/vue-json-pretty.js:1:1
    at Object../node_modules/vue-json-pretty/lib/vue-json-pretty.js (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/node_modules/vue-json-pretty/lib/vue-json-pretty.js:1:1)
    at __webpack_require__ (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/webpack/bootstrap:19:1)
    at Object../src/contrib.js (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/src/contrib.js:2:1)
    at __webpack_require__ (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/webpack/bootstrap:19:1)
    at Object../tests/unit/setup.js (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/tests/unit/setup.js:10:1)
    at __webpack_require__ (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/webpack/bootstrap:19:1)
    at Object../tests/unit/specs/ConfigAlert.spec.js (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/tests/unit/specs/ConfigAlert.spec.js:5:1)
    at __webpack_require__ (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/webpack/bootstrap:19:1)
    at run (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/node_modules/mochapack/lib/entry.js:3:1)
    at Array.forEach (<anonymous>)
    at Object../node_modules/mochapack/lib/entry.js (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/node_modules/mochapack/lib/entry.js:10:1)
    at __webpack_require__ (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/webpack/bootstrap:19:1)
    at /home/sano/dkwork3/elastalert_praeco/praeco/dist/js/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/sano/dkwork3/elastalert_praeco/praeco/dist/js/main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.module_1.default._extensions.<computed> [as .js] (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/mochapack/src/util/registerRequireHook.ts:106:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/mocha/lib/mocha.js:809:10)
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/mochapack/src/runner/TestRunner.ts:105:23
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/mochapack/src/webpack/compiler/registerReadyCallback.ts:14:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/tapable/lib/Hook.js:154:20)
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/webpack/lib/Compiler.js:298:10
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/webpack/lib/Compiler.js:485:14
    at _next0 (eval at create (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/copy-webpack-plugin/dist/index.js:115:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/tapable/lib/Hook.js:154:20)
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/webpack/lib/Compiler.js:482:27
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/neo-async/async.js:2818:7
    at done (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /home/sano/dkwork3/elastalert_praeco/praeco/node_modules/webpack/lib/Compiler.js:464:33
    at MemoryFileSystem.writeFile (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/webpack/lib/Compiler.js:462:30)
    at Immediate._onImmediate (/home/sano/dkwork3/elastalert_praeco/praeco/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at processImmediate (internal/timers.js:461:21)

 ERROR  mochapack exited with code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! praeco@1.5.1 test:unit: `vue-cli-service test:unit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the praeco@1.5.1 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sano/.npm/_logs/2020-12-16T18_24_22_878Z-debug.log
```

**Comment by nsano-rururu** [comment]
This issue is closed because it is managed by the following issue
https://github.com/johnsusek/praeco/issues/292
