### ISSUE TITLE
When trying to add new rule - failed with  "Error saving config, are all fields filled out?"

### ISSUE THREAD

**Issue by i-kit** [johnsusek/praeco#374]
## 🐛 Summary
When I tried to added new rule it's fail "Error saving config, are all fields filled out?"
(Bug summary)

## 👀 Steps
docker-compose up
open page
try to add rule

## 🆗 Expected
new rule added
## 🚑 Actual
alert_1  | 13:29:26.962Z ERROR elastalert-server:
elastalert_1  |     TestController:  Failed to test rule with error: INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
elastalert_1  |                 To send them but remain verbose, use --verbose instead.
elastalert_1  |     
elastalert_1  |     Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
elastalert_1  |         return _run_code(code, main_globals, None,
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
elastalert_1  |         exec(code, run_globals)
elastalert_1  |       File "/opt/elastalert/elastalert/test_rule.py", line 460, in <module>
elastalert_1  |         main()
elastalert_1  |       File "/opt/elastalert/elastalert/test_rule.py", line 456, in main
elastalert_1  |         test_instance.run_rule_test()
elastalert_1  |       File "/opt/elastalert/elastalert/test_rule.py", line 413, in run_rule_test
elastalert_1  |         rule_yaml = conf['rules_loader'].load_yaml(args.file)
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 210, in load_yaml
elastalert_1  |         if 'filter' in rule and 'filter' in loaded:
elastalert_1  |     TypeError: argument of type 'NoneType' is not iterable

**Comment by i-kit** [comment]
I checked - seems all field exist ...

**Comment by nsano-rururu** [comment]
Have you set write permission for the rules directory?

```
mkdir -p rules rule_templates
chmod -R 777 rules rule_templates
```

**Comment by i-kit** [comment]
Just did, still same:
astalert_1  | 14:19:00.275Z ERROR elastalert-server:
elastalert_1  |     TestController:  Failed to test rule with error: INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
elastalert_1  |                 To send them but remain verbose, use --verbose instead.
elastalert_1  |     
elastalert_1  |     Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
elastalert_1  |         return _run_code(code, main_globals, None,
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
elastalert_1  |         exec(code, run_globals)
elastalert_1  |       File "/opt/elastalert/elastalert/test_rule.py", line 460, in <module>
elastalert_1  |         main()
elastalert_1  |       File "/opt/elastalert/elastalert/test_rule.py", line 456, in main
elastalert_1  |         test_instance.run_rule_test()
elastalert_1  |       File "/opt/elastalert/elastalert/test_rule.py", line 413, in run_rule_test
elastalert_1  |         rule_yaml = conf['rules_loader'].load_yaml(args.file)
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 210, in load_yaml
elastalert_1  |         if 'filter' in rule and 'filter' in loaded:
elastalert_1  |     TypeError: argument of type 'NoneType' is not iterable
elastalert_1  |

**Comment by nsano-rururu** [comment]
As a reminder, is elasticsearch running?

**Comment by nsano-rururu** [comment]
```
docker-compose down
docker rmi praecoapp/elastalert-server:latest
docker rmi praecoapp/praeco:latest
docker pull praecoapp/elastalert-server:latest
docker pull praecoapp/praeco:latest
docker-compose up
```

**Comment by i-kit** [comment]
Just screen of my settings, will try to rebuild docker.
![image](https://user-images.githubusercontent.com/59962283/119844654-4b15c800-bf11-11eb-84fb-49ccb32d3064.png)

**Comment by nsano-rururu** [comment]
>Just screen of my settings, will try to rebuild docker.

What do you mean?

**Comment by nsano-rururu** [comment]
Cannot be reproduced.
![1](https://user-images.githubusercontent.com/22293449/119853992-a369bb80-bf4b-11eb-9d14-ef1f3353393c.PNG)
![2](https://user-images.githubusercontent.com/22293449/119854003-a5cc1580-bf4b-11eb-99c1-0af47f664876.PNG)
![3](https://user-images.githubusercontent.com/22293449/119854008-a795d900-bf4b-11eb-895e-410d1f5890bb.PNG)
![3](https://user-images.githubusercontent.com/22293449/119854079-baa8a900-bf4b-11eb-987c-4846397574eb.JPG)
![5](https://user-images.githubusercontent.com/22293449/119854109-c2684d80-bf4b-11eb-8e53-f432fd7a066e.PNG)
![6](https://user-images.githubusercontent.com/22293449/119854114-c4caa780-bf4b-11eb-8161-dbb5f2c802ab.JPG)

**Comment by nsano-rururu** [comment]
The docker-compose settings I'm using in my environment a while back are listed on the wiki.
[docker compose sample(telegram)](https://github.com/johnsusek/praeco/wiki/docker-compose-sample(telegram))

**Comment by i-kit** [comment]
Possible depend to use behind nginx ... Will try directly ...

**Comment by nsano-rururu** [comment]
Is that so. If you do it yourself. Until you are satisfied. I can only say that. Because I provided the information that I can provide.

**Comment by i-kit** [comment]
Tried locally in docker - still have same issue ... Strange ...

**Comment by nsano-rururu** [comment]
All commands and settings when tried with docker. If you don't know what kind of environment you are in, you can't do anything more.

**Comment by nsano-rururu** [comment]
If the information cannot be provided, the issue will be closed.

**Comment by i-kit** [comment]
Possible wrongly said:
I started locally now as docker and connected over 127.0.0.1:8888, but still has same issue. No Nginx or another proxies ...

**Comment by nsano-rururu** [comment]
Not in the README = I want to use it in an environment where operation has not been confirmed. I see, it can't be supported.

**Comment by i-kit** [comment]
Ok I finally got it working - seems add config in BaseRules.json is the must - I though we can postpone it ...

**Comment by i-kit** [comment]
Some stupid question: can O create filter like:
num_events: 10
timeframe:
  hours: 4
So it's will send alert if something happen more as 4 times ...

**Comment by nsano-rururu** [comment]
Then num_events is 4, right? .. Why is it 10? ..

**Comment by nsano-rururu** [comment]
With that designation, it looks like an alert notification if it occurs 10 times or more in 4 hours.

**Comment by nsano-rururu** [comment]
Please do the setting you want to set there. that's all. Goodbye.
![WS000000](https://user-images.githubusercontent.com/22293449/120206534-48470a00-c266-11eb-9a2b-cee07451a707.JPG)
![WS000001](https://user-images.githubusercontent.com/22293449/120206543-4b41fa80-c266-11eb-8c03-135f2df5ae77.JPG)
![WS000002](https://user-images.githubusercontent.com/22293449/120206554-4d0bbe00-c266-11eb-8148-f02e81d76833.JPG)

**Comment by i-kit** [comment]
Sorry yes 10 notification in last 4h - this is work in elastic-alert config ...

**Comment by i-kit** [comment]
Seems this what I need ! Testing, perfect!

**Comment by csroin** [comment]
@i-kit This seems to be a real issue. Can you share the fix?

I have created my helm chart, it was working fine with Elastalert-20170313 and praeco-1.8.1. Updating the Docker images of praeco to  1.8.6  & ElastalertServer to 20170513 is giving me a similar error.

**Comment by nsano-rururu** [comment]
@csroin

ElastalertServer to 20170513
What is 20170513? .. Is it a mistake?
Which docker image are you using?

**Comment by nsano-rururu** [comment]
@csroin

I don't even know Elastalert-20170313. what is it. that is

**Comment by nsano-rururu** [comment]
@csroin

Please tell me the rules you are using. If you can't reproduce it, you can't do anything, but are you satisfied with it?

**Comment by nsano-rururu** [comment]
@csroin

Please raise another issue.

**Comment by csroin** [comment]
@nsano-rururu  Sorry, I was referring to the Docker tag. 
praecoapp/elastalert-server:20210517 and praeco 1.8.6 (Updating to this, is giving me the error. )
praecoapp/elastalert-server:20210317 and praeco 1.8.1 (Is working fine)

Sure I will open another issue. First trying to fix it by adding few entries in BaseRule.config

**Comment by nsano-rururu** [comment]
@csroin

Are you using query_key?

**Comment by nsano-rururu** [comment]
@csroin

If you are using query_key, you need to take the following actions. Since it is possible to set multiple settings, it is now an array instead of a character string.

https://github.com/johnsusek/praeco/releases/tag/1.8.3
>Add option to use multiple query keys
Since query_key has been changed to an array, if it has already been set, an error will occur when reading the rule. Please delete query_key from the rule before the version upgrade and set it again after the version upgrade.

**Comment by nsano-rururu** [comment]
@csroin

If the cause is different, you can't tell without knowing what rule you're using. Would you please provide the rules generated by praeco? Please change the authentication information etc. to different characters such as xxxx before pasting.

**Comment by nsano-rururu** [comment]
@csroin 

What is in BaseRule.config?

**Comment by csroin** [comment]
@nsano-rururu 

The issue was not with query_key. I don't have any rules created yet, assume was just deploying from scratch. 
Empty /opt/elastalert/rules/BaseRule.config file is creating error in case of newer versions. 

Adding any line like **slack_webhook_url: ''**   fixes the issue.

**Comment by nsano-rururu** [comment]
@csroin 

I haven't changed anything about BaseRule.config, so I can't say anything, but there is a possibility that something is written. In the next version, I will try to prevent an error even if BaseRule.config is empty or does not exist.

**Comment by csroin** [comment]
Thanks @nsano-rururu
