### ISSUE TITLE
Praeco install error

### ISSUE THREAD

**Issue by ozgursuder** [johnsusek/praeco#406]
INFO  Starting development server...
 ERROR  Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "type": "javascript/auto",
  "include": [
    {}
  ],
  "use": []
}
Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "type": "javascript/auto",
  "include": [
    {}
  ],
  "use": []
}
    at checkResourceSource (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:167:11)
    at Function.normalizeRule (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:198:4)
    at /opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:110:20
    at Array.map (<anonymous>)
    at Function.normalizeRules (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:109:17)
    at new RuleSet (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:104:24)
    at new NormalModuleFactory (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModuleFactory.js:115:18)
    at Compiler.createNormalModuleFactory (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:636:31)
    at Compiler.newCompilationParams (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:653:30)
    at Compiler.compile (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:661:23)
    at /opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/praeco/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/opt/praeco/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/Watching.js:41:32)
    at /opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/Watching.js:33:9
    at Compiler.readRecords (/opt/praeco/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:529:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! praeco@1.8.10 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the praeco@1.8.10 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ozgursuder** [comment]
Prarco start command 
npm run serve

**Comment by nsano-rururu** [comment]
Read the document

**Comment by nsano-rururu** [comment]
Get the latest from github. I am fixing it.
