### ISSUE TITLE
node 16 to node 18

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#449]
Node 16 will reach end of life (EoL) on September 11, 2023

---

**praeco**

- [x] node:lts-gallium  → node:lts-hydrogen

[GLIBC_2.27 not found while installing Node on Amazon EC2 instance](https://stackoverflow.com/questions/72022527/glibc-2-27-not-found-while-installing-node-on-amazon-ec2-instance)

- [x] @vue/cli* 4.5.19 → 5.0.8
- [x] webpack 4.x to 5.x

**Comment by nsano-rururu** [comment]
- I get a GLIBC not found error. OS version upgrade is required to build node 18.
example)
Amazon Linux 2 → 2022
Ubuntu 18.04 → Ubuntu 22.04

- It is necessary to modify the description of Dockerfile

before
```sh
FROM node:lts-gallium AS base

RUN apt-get update
RUN apt-get install -y nginx
```
after
```sh
FROM node:lts-hydrogen AS base

RUN apt update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt install -y nginx
```

- It doesn't work with webpack4.x. Requires webpack5.x and vue.config.js setting addition `output.hashFunction: "xxhash64"`. It seems to be fixed in webpack6

add Dockerfile
```
RUN export NODE_OPTIONS=--openssl-legacy-provider
```

error  message

```sh
> vue-cli-service build --openssl-legacy-provide


-  Building for production...
Error: Digest method not supported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/tmp/nginx/praeco/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/nginx/praeco/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/nginx/praeco/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/nginx/praeco/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/nginx/praeco/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/tmp/nginx/praeco/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /tmp/nginx/praeco/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: Digest method not supported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/tmp/nginx/praeco/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/nginx/praeco/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/nginx/praeco/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/nginx/praeco/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/nginx/praeco/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/tmp/nginx/praeco/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /tmp/nginx/praeco/node_modules/cache-loader/dist/index.js:147:7
    at /tmp/nginx/praeco/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:197:23)
```
