### ISSUE TITLE
vue3 support for vue-at

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#454]
It seems that it is compatible with vue3, so I plan to wait for it

- [ ] src/components/config/alert/ConfigAlertSubjectBody.vue
- [ ] package.json

---

error

```
vue-at.js?a1f5:471 Uncaught TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__ (vue-at.js?a1f5:471:1)
    at eval (vue-at.js?a1f5:658:1)
    at eval (vue-at.js?a1f5:1261:1)
    at eval (vue-at.js?a1f5:1264:1)
    at ./node_modules/vue-at/dist/vue-at.js (chunk-vendors.js:24182:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/components/config/alert/ConfigAlertSubjectBody.vue?vue&type=script&lang=js:11:64)
    at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/components/config/alert/ConfigAlertSubjectBody.vue?vue&type=script&lang=js (app.js:1550:1)
    at __webpack_require__ (app.js:849:30)
```

**Comment by nsano-rururu** [comment]
It seems to be compatible with vue3, so I will close it
