### ISSUE TITLE
Data folder missing in api.config.json and docker-compose.yml files blocks elastalertserver starting

### ISSUE THREAD

**Issue by Azer-BA** [johnsusek/praeco#466]
## 🐛 Summary

Hi,

It seems that the configuration part concerning the data directory is missing, is this normal? shouldn't it be added to the api.config.json and docker-compose.yml files in this repo?

Without data directory the elastalert-server will not start and we get these errors:

```
praeco-elastalert-1  | 09:45:50.999Z  INFO elastalert-server:
praeco-elastalert-1  |     ProcessController:  Reading Elastic 7 index mappings:
praeco-elastalert-1  |     Reading index mapping 'es_mappings/7/silence.json'
praeco-elastalert-1  |     Reading index mapping 'es_mappings/7/elastalert_status.json'
praeco-elastalert-1  |     Reading index mapping 'es_mappings/7/elastalert.json'
praeco-elastalert-1  |     Reading index mapping 'es_mappings/7/past_elastalert.json'
praeco-elastalert-1  |     Reading index mapping 'es_mappings/7/elastalert_error.json'
praeco-elastalert-1  |     Index praeco_elastalert_status already exists. Skipping index creation.
praeco-elastalert-1  |     
praeco-elastalert-1  | 09:45:50.999Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
praeco-elastalert-1  | 09:45:51.000Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
praeco-elastalert-1  | 09:45:51.008Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 37)
praeco-elastalert-1  | 09:45:51.031Z ERROR elastalert-server:
praeco-elastalert-1  |     Server:  Starting server failed with error: TypeError: Cannot read properties of undefined (reading 'relative')
praeco-elastalert-1  |         at ElastalertServer.getDataFolder (/opt/elastalert-server/src/elastalert_server.js:142:28)
praeco-elastalert-1  |         at TestController._getTestFolder (/opt/elastalert-server/src/controllers/test/index.js:169:35)
praeco-elastalert-1  |         at new TestController (/opt/elastalert-server/src/controllers/test/index.js:18:28)
praeco-elastalert-1  |         at callback (/opt/elastalert-server/src/elastalert_server.js:98:32)
praeco-elastalert-1  |         at forEach (/opt/elastalert-server/src/common/config/server_config.js:59:9)
praeco-elastalert-1  |         at Array.forEach (<anonymous>)
praeco-elastalert-1  |         at /opt/elastalert-server/src/common/config/server_config.js:58:22
praeco-elastalert-1  | 09:45:51.031Z  INFO elastalert-server: Server:  Stopping server
praeco-elastalert-1  | 09:45:51.032Z  INFO elastalert-server: ProcessController:  Stopping ElastAlert (PID: 37)
praeco-elastalert-1  | 09:45:51.032Z  INFO elastalert-server: Server:  Server stopped. Bye!
```

After adding the configuration lines below it works and the elastalert-server start.

**config/api.config.json**
```
  "dataPath": {
    "relative": true,
    "path": "/data"
  },
```

**docker-compose.yml**
```
    volumes:
      - ./data:/opt/elastalert/data
```
## 👀 Operating environment

- Docker
- elasticsearch version : 7.17.1
- version of praeco : 1.8.11
- elastalert-server docker image tag name : Concerns images after 20210825

Thank you for your work and this tool,

Regards,

**Comment by nsano-rururu** [comment]
dataPath? What is it? There is no such setting. Please read the documentation
