### ISSUE TITLE
Vue-CLI to Vite

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#478]
Vite
https://ja.vitejs.dev/

Webpack to Vite
https://github.com/originjs/webpack-to-vite

---
- [ ] vite.config.js
- [ ] package.json
- [ ] package-lock.json
- [ ] index.html
https://dev.classmethod.jp/articles/vite-index-html-read-env-variables/
- [ ] process.env.VUE_APP_BASE_URL to  import.meta.env.VITE_BASE_URL
https://qiita.com/manak1/items/9f61d514980ab1ec2e19

**Comment by nsano-rururu** [comment]
Do not correspond

**Comment by nsano-rururu** [comment]
```sh

✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "vue-cron-editor-buefy". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue-cron-editor-buefy". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40970:10:
      40970 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40970:11)
    at resolvePackageEntry (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40966:9)
    at tryNodeResolve (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40773:20)
    at Context.resolveId (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40581:28)
    at Object.resolveId (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39254:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39466:26)
    at async /home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39626:34
    at async callback (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:933:28)
    at async handleRequest (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:713:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39616:18:
      39616 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39616:19)
    at handlePlugins (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:855:23)
    at Object.buildOrServe (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:1149:7)
    at /home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:2109:14)
    at Object.build (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:1956:51)
    at /home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39414:54
    at Array.map (<anonymous>)
    at scanImports (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39414:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async discoverProjectDependencies (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39855:31)
    at async Timeout.warmUp [as _onTimeout] (/home/sano2/dkwork3/praeco-toVite/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50469:36)

  The plugin "vite:dep-scan" was triggered by this import

    script:/home/sano2/dkwork3/praeco-toVite/src/components/config/ConfigLimitExcecution.vue?id=0:2:31:
      2 │ import VueCronEditorBuefy from 'vue-cron-editor-buefy';
        ╵                                ~~~~~~~~~~~~~~~~~~~~~~~


 ERROR  Build failed with 1 error:                                                                                                                                  22:54:17
node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40970:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "vue-cron-editor-buefy". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue-cron-editor-buefy". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by nsano-rururu** [comment]
```
✘ [ERROR] Could not resolve "./later-cov"

    node_modules/later/index.js:8:35:
      8 │ require(process.env['LATER_COV'] ? "./later-cov" : "./later");
        ╵                                    ~~~~~~~~~~~~~


 ERROR  23:01:52 [vite] error while updating dependencies:                                                                                                          23:01:52
Error: Build failed with 1 error:
node_modules/later/index.js:8:35: ERROR: Could not resolve "./later-cov"
    at failureErrorWithLog (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:1624:15)
    at /home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:1264:7)
    at /home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:1377:14
    at /home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/home/sano2/dkwork3/praeco-toVite/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by nsano-rururu** [comment]
https://vueschool.io/articles/vuejs-tutorials/how-to-migrate-from-vue-cli-to-vite/

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco/pull/716

**Comment by nsano-rururu** [comment]
In vue2.7+element-ui, the following settings are required to resolve the issue where the value of el-table is not displayed.
```
// vite.config.js
resolve: {
        extensions: ['.js', '.vue', '.jsx', 'tsx', '.json'],
        alias: {
            vue: 'vue/dist/vue.esm.js',
        },
    },
```
