### ISSUE TITLE
Fresh install - TypeError: Cannot read properties of undefined (reading 'relative')

### ISSUE THREAD

**Issue by vp-lab** [johnsusek/praeco#485]
## 🐛 Describe the bug

praecoapp/praeco:latest
praecoapp/elastalert-server:latest

When I try to fresh install, I get this error.
```
[root@docker praeco]# docker-compose up
[+] Running 2/0
 ⠿ Container praeco-webapp-1      Created                                                                                                                 0.0s
 ⠿ Container praeco-elastalert-1  Created                                                                                                                 0.0s
Attaching to praeco-elastalert-1, praeco-webapp-1
praeco-webapp-1      | Starting Nginx
praeco-elastalert-1  | 
praeco-elastalert-1  | > @bitsensor/elastalert@0.0.14 start
praeco-elastalert-1  | > sh ./scripts/start.sh
praeco-elastalert-1  | 
praeco-elastalert-1  | 07:37:13.902Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
praeco-elastalert-1  | 07:37:13.904Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
praeco-elastalert-1  | 07:37:13.905Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
praeco-elastalert-1  | 07:37:13.923Z  INFO elastalert-server: Router:  Listening for GET request on /.
praeco-elastalert-1  | 07:37:13.923Z  INFO elastalert-server: Router:  Listening for GET request on /status.
praeco-elastalert-1  | 07:37:13.923Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
praeco-elastalert-1  | 07:37:13.924Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
praeco-elastalert-1  | 07:37:13.926Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id*.
praeco-elastalert-1  | 07:37:13.926Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id*.
praeco-elastalert-1  | 07:37:13.926Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id*.
praeco-elastalert-1  | 07:37:13.926Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
praeco-elastalert-1  | 07:37:13.927Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id*.
praeco-elastalert-1  | 07:37:13.927Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id*.
praeco-elastalert-1  | 07:37:13.927Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id*.
praeco-elastalert-1  | 07:37:13.927Z  INFO elastalert-server: Router:  Listening for PUT request on /folders/:type/:path*.
praeco-elastalert-1  | 07:37:13.927Z  INFO elastalert-server: Router:  Listening for DELETE request on /folders/:type/:path*.
praeco-elastalert-1  | 07:37:13.927Z  INFO elastalert-server: Router:  Listening for POST request on /test.
praeco-elastalert-1  | 07:37:13.928Z  INFO elastalert-server: Router:  Listening for POST request on /silence/:path*.
praeco-elastalert-1  | 07:37:13.928Z  INFO elastalert-server: Router:  Listening for GET request on /config.
praeco-elastalert-1  | 07:37:13.928Z  INFO elastalert-server: Router:  Listening for POST request on /config.
praeco-elastalert-1  | 07:37:13.928Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert.
praeco-elastalert-1  | 07:37:13.928Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_status.
praeco-elastalert-1  | 07:37:13.928Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/silence.
praeco-elastalert-1  | 07:37:13.928Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_error.
praeco-elastalert-1  | 07:37:13.929Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/past_elastalert.
praeco-elastalert-1  | 07:37:13.929Z  INFO elastalert-server: Router:  Listening for GET request on /indices.
praeco-elastalert-1  | 07:37:13.929Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
praeco-elastalert-1  | 07:37:13.929Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
praeco-elastalert-1  | 07:37:13.929Z  INFO elastalert-server: Router:  Listening for GET request on /config.
praeco-elastalert-1  | 07:37:13.932Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
praeco-elastalert-1  | 07:37:13.932Z  INFO elastalert-server: ProcessController:  Creating index
praeco-elastalert-1  | 07:37:14.206Z  INFO elastalert-server:
praeco-elastalert-1  |     ProcessController:  Reading Elastic 8 index mappings:
praeco-elastalert-1  |     Reading index mapping 'es_mappings/8/silence.json'
praeco-elastalert-1  |     Reading index mapping 'es_mappings/8/elastalert_status.json'
praeco-elastalert-1  |     Reading index mapping 'es_mappings/8/elastalert.json'
praeco-elastalert-1  |     Reading index mapping 'es_mappings/8/past_elastalert.json'
praeco-elastalert-1  |     Reading index mapping 'es_mappings/8/elastalert_error.json'
praeco-elastalert-1  |     Index praeco_elastalert_status already exists. Skipping index creation.
praeco-elastalert-1  |     
praeco-elastalert-1  | 07:37:14.206Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
praeco-elastalert-1  | 07:37:14.207Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
praeco-elastalert-1  | 07:37:14.211Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 37)
praeco-elastalert-1  | 07:37:14.229Z ERROR elastalert-server:
praeco-elastalert-1  |     Server:  Starting server failed with error: TypeError: Cannot read properties of undefined (reading 'relative')
praeco-elastalert-1  |         at ElastalertServer.getDataFolder (/opt/elastalert-server/src/elastalert_server.js:141:28)
praeco-elastalert-1  |         at TestController._getTestFolder (/opt/elastalert-server/src/controllers/test/index.js:169:35)
praeco-elastalert-1  |         at new TestController (/opt/elastalert-server/src/controllers/test/index.js:18:28)
praeco-elastalert-1  |         at callback (/opt/elastalert-server/src/elastalert_server.js:97:32)
praeco-elastalert-1  |         at forEach (/opt/elastalert-server/src/common/config/server_config.js:59:9)
praeco-elastalert-1  |         at Array.forEach (<anonymous>)
praeco-elastalert-1  |         at /opt/elastalert-server/src/common/config/server_config.js:58:22
praeco-elastalert-1  | 07:37:14.229Z  INFO elastalert-server: Server:  Stopping server
praeco-elastalert-1  | 07:37:14.229Z  INFO elastalert-server: ProcessController:  Stopping ElastAlert (PID: 37)
praeco-elastalert-1  | 07:37:14.230Z  INFO elastalert-server: Server:  Server stopped. Bye!
praeco-elastalert-1 exited with code 0
```

## 👀 Steps to reproduce

1. git clone https://github.com/johnsusek/praeco.git
2. mkdir -p rules rule_templates
3. chmod -R 777 rules rule_templates
4. change IP in docker-compose: - 'elasticsearch:192.168.3.161'
5. docker-compose up
6. elastalert won't start, only web it's started

## 🆗 Expected behavior

1. git clone https://github.com/johnsusek/praeco.git
2. mkdir -p rules rule_templates
3. chmod -R 777 rules rule_templates
4. change IP in docker-compose: **- 'elasticsearch:192.168.3.161'**
5. docker-compose up
6. **both containers to be started**

## Environments

docker-compose.yml
```
version: '3'

services:
  elastalert:
    image: 'praecoapp/elastalert-server'
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
    extra_hosts:
      - 'elasticsearch:192.168.3.161'

  webapp:
    image: 'praecoapp/praeco'
    ports:
      - 8080:8080
#    environment:
#      VUE_APP_BASE_URL: /my-path/
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
```

cat /etc/os-release
```
NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"
ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"
```

**Comment by nsano-rururu** [comment]
It's just no good not to specify an IP address that can be accessed from the docker container. Don't ask the same question!
