### ISSUE TITLE
Vue3 support for vue-query-builder

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#566]
- [x] vue2 to 3
- [x] Bootstrap 3 to 5
- [ ] warning message

```sh
Feature flag __VUE_PROD_HYDRATION_MISMATCH_DETAILS__ is not explicitly defined. You are running the esm-bundler build of Vue, which expects these compile-time feature flags to be globally injected via the bundler config in order to get better tree-shaking in the production bundle.

For more details, see https://link.vuejs.org/feature-flags. runtime-core.esm-bundler.js:5227
```

**Comment by nsano-rururu** [comment]
https://github.com/nsano-rururu/vue-query-builder/tree/v0.6.1vue3

**Comment by nsano-rururu** [comment]
```sh
$ npm run test:unit

> vue-query-builder@0.6.1 test:unit
> vue-cli-service test:unit

● Validation Error:

  Module vue-jest in the transform option was not found.
         <rootDir> is: /home/sano2/dkwork3/vue-query-builder

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

---

```sh
$ npm run test:e2e

> vue-query-builder@0.6.1 test:e2e
> vue-cli-service test:e2e

 INFO  Starting e2e tests...
 INFO  Starting development server...


 WARNING  Compiled with 3 warnings                                                                                                                                                                           22:55:12

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/chunk-vendors.6f009d40.js (318 KiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (334 KiB)
      js/chunk-vendors.6f009d40.js
      css/app.2904765c.css
      js/app.5bc22c7a.js


 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://172.16.0.76:8080/

  App is served in production mode.
  Note this is for preview or E2E testing only.

It looks like this is your first time using Cypress: 3.8.3

 ✔  Verified Cypress! /home/sano2/.cache/Cypress/3.8.3/Cypress

Opening Cypress...
[Error: ENAMETOOLONG: name too long, stat 'tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests'

] {
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'stat',
  path: 'tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests'
}
Error: ENAMETOOLONG: name too long, stat 'tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests/e2e/specs/tests'
```
---

```sh
 npm run docs:dev

> vue-query-builder@0.6.1 docs:dev
> vuepress dev docs

/home/sano2/dkwork3/vue-query-builder/node_modules/vue-server-renderer/index.js:8
  throw new Error(
  ^

Error: 

Vue packages version mismatch:

- vue@3.4.5
- vue-server-renderer@2.7.14

This may cause things to work incorrectly. Make sure to use the same version for both.

    at Object.<anonymous> (/home/sano2/dkwork3/vue-query-builder/node_modules/vue-server-renderer/index.js:8:9)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/sano2/dkwork3/vue-query-builder/node_modules/@vuepress/core/lib/node/build/index.js:11:34)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/sano2/dkwork3/vue-query-builder/node_modules/@vuepress/core/lib/node/App.js:21:22)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
```

---

```sh
 npm run docs:build

> vue-query-builder@0.6.1 docs:build
> vuepress build docs

/home/sano2/dkwork3/vue-query-builder/node_modules/vue-server-renderer/index.js:8
  throw new Error(
  ^

Error: 

Vue packages version mismatch:

- vue@3.4.5
- vue-server-renderer@2.7.14

This may cause things to work incorrectly. Make sure to use the same version for both.

    at Object.<anonymous> (/home/sano2/dkwork3/vue-query-builder/node_modules/vue-server-renderer/index.js:8:9)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/sano2/dkwork3/vue-query-builder/node_modules/@vuepress/core/lib/node/build/index.js:11:34)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/sano2/dkwork3/vue-query-builder/node_modules/@vuepress/core/lib/node/App.js:21:22)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
```

**Comment by nsano-rururu** [comment]
https://github.com/nsano-rururu/vue-query-builder/pull/13
