### ISSUE TITLE
node 18 to 20

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#608]
- [x] praeco
docker image: node:lts-iron
https://github.com/johnsusek/praeco/commit/d861257fe73ff99266ccc1b7f85047e3039ad396
- [x] elastalert-server
docker image: node:20.12.2-alpine3.19
https://github.com/johnsusek/elastalert-server/commit/62e0203c9cb12b95a115604afc9ca11bc01cb1ce

**Comment by nsano-rururu** [comment]
```sh
Step 8/15 : RUN npm install --legacy-peer-deps --loglevel error
 ---> Running in 052f99045728
npm notice 
npm notice New patch version of npm available! 10.2.3 -> 10.2.5
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.5>
npm notice Run `npm install -g npm@10.2.5` to update!
npm notice 
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-cloneD68hV0/node_modules/esbuild
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node install.js
npm ERR! npm ERR! node:internal/errors:563
npm ERR! npm ERR!     ErrorCaptureStackTrace(err);
npm ERR! npm ERR!     ^
npm ERR! npm ERR! 
npm ERR! npm ERR! <ref *1> Error: spawnSync /root/.npm/_cacache/tmp/git-cloneD68hV0/node_modules/esbuild/bin/esbuild ETXTBSY
npm ERR! npm ERR!     at Object.spawnSync (node:internal/child_process:1124:20)
npm ERR! npm ERR!     at spawnSync (node:child_process:876:24)
npm ERR! npm ERR!     at Object.execFileSync (node:child_process:919:15)
npm ERR! npm ERR!     at validateBinaryVersion (/root/.npm/_cacache/tmp/git-cloneD68hV0/node_modules/esbuild/install.js:94:32)
npm ERR! npm ERR!     at /root/.npm/_cacache/tmp/git-cloneD68hV0/node_modules/esbuild/install.js:242:5 {
npm ERR! npm ERR!   errno: -26,
npm ERR! npm ERR!   code: 'ETXTBSY',
npm ERR! npm ERR!   syscall: 'spawnSync /root/.npm/_cacache/tmp/git-cloneD68hV0/node_modules/esbuild/bin/esbuild',
npm ERR! npm ERR!   path: '/root/.npm/_cacache/tmp/git-cloneD68hV0/node_modules/esbuild/bin/esbuild',
npm ERR! npm ERR!   spawnargs: [ '--version' ],
npm ERR! npm ERR!   error: [Circular *1],
npm ERR! npm ERR!   status: null,
npm ERR! npm ERR!   signal: null,
npm ERR! npm ERR!   output: null,
npm ERR! npm ERR!   pid: 0,
npm ERR! npm ERR!   stdout: null,
npm ERR! npm ERR!   stderr: null
npm ERR! npm ERR! }
npm ERR! npm ERR! 
npm ERR! npm ERR! Node.js v20.10.0
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-01-03T11_49_16_390Z-debug-0.log

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-01-03T11_47_16_163Z-debug-0.log
The command '/bin/sh -c npm install --legacy-peer-deps --loglevel error' returned a non-zero code: 1
```
