### ISSUE TITLE
node 20 to 22(LTS)

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#639]
- [ ] praeco 2.0.0
- [x] elastalert-server

**Comment by nsano-rururu** [comment]
**elastalert-server**

22.12 ： OK
23.5  ： NG

**praeco**

Canvas 2.11.2, which uses js-dom, does not support node22. js-dom does not support canvas 3.x.

22.12 ： NG
23.5  ： NG

```sh
Step 8/15 : RUN npm install --legacy-peer-deps --loglevel error
 ---> Running in 7f6f6dc5cd7a
npm error code 1
npm error path /tmp/nginx/praeco/node_modules/canvas
npm error command failed
npm error command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/tmp/nginx/praeco/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/nginx/praeco/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
npm error (node:203) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz 
npm error Package pangocairo was not found in the pkg-config search path.
npm error Perhaps you should add the directory containing `pangocairo.pc'
npm error to the PKG_CONFIG_PATH environment variable
npm error Package 'pangocairo', required by 'virtual:world', not found
npm error gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:317:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:524:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm error gyp ERR! System Linux 6.8.0-1015-aws
npm error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/tmp/nginx/praeco/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/tmp/nginx/praeco/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"
npm error gyp ERR! cwd /tmp/nginx/praeco/node_modules/canvas
npm error gyp ERR! node -v v22.12.0
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok 
npm error node-pre-gyp ERR! build error 
npm error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/tmp/nginx/praeco/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/nginx/praeco/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/nginx/praeco/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:524:28)
npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm error node-pre-gyp ERR! System Linux 6.8.0-1015-aws
npm error node-pre-gyp ERR! command "/usr/local/bin/node" "/tmp/nginx/praeco/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm error node-pre-gyp ERR! cwd /tmp/nginx/praeco/node_modules/canvas
npm error node-pre-gyp ERR! node -v v22.12.0
npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm error node-pre-gyp ERR! not ok
npm notice
npm notice New major version of npm available! 10.9.0 -> 11.0.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.0.0
npm notice To update run: npm install -g npm@11.0.0
npm notice
npm error A complete log of this run can be found in: /root/.npm/_logs/2025-01-04T13_29_41_595Z-debug-0.log
The command '/bin/sh -c npm install --legacy-peer-deps --loglevel error' returned a non-zero code: 1
```

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco/pull/711

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco/tree/2.0.0
